Update getbtpcli

diff --git a/getbtpcli b/getbtpcli
--- a/getbtpcli
+++ b/getbtpcli
@@ -1,36 +1,19 @@
 #!/usr/bin/env bash
-
-# getbtpcli - Get btp CLI. Specify a version, or have it default to
-# getting the latest. Has a test mode (-t or --test) to just retrieve
-# and show what the version is (only really makes sense when defaulting
-# to latest), without installing.
-
-# Usage: getbtpcli [-t|--test] [version]
-# Examples:
-# getbtpcli         gets & installs latest version; shows the version nr
-# getbtpcli --test  gets & shows what the latest version is; no install
-# getbtpcli 2.8.0   gets & installs version 2.8.0, shows the version nr
-
 set -o errexit
 
 declare PLATFORM
 PLATFORM="$(uname -s)"
 
 declare -r ARCH="${PLATFORM,,}-amd64"
-declare -r TARGETDIR="$HOME/bin"
 declare -r LICENCE="tools.hana.ondemand.com/developer-license-3_1.txt"
 
 
 retrieve() {
 
   # Download tarball of latest version and extract the btp binary
+  local filename="btp-cli-$ARCH-latest.tar.gz"
 
-  local desired=$1
-  local tempdir=$2
-  local filename="btp-cli-$ARCH-$desired.tar.gz"
-
-  cd "$tempdir" \
-    && curl \
+  curl \
       --fail \
       --silent \
       --location \
@@ -43,63 +26,15 @@ retrieve() {
       --gunzip \
       --strip-components 1 \
       "$ARCH/btp"
-
-}
-
-get_version() {
-
-  # Determine the version (uses the proper grep, from GNU). We need to point to a temp, empty
-  # config file because older versions of btp don't like seeing newer versions of any config content.
-
-  local tempdir=$1
-  "$tempdir/btp" --config "$tempdir/config" --version 2> /dev/null | grep -P -o '(?<=v)\d+\.\d+\.\d+'
+    && mv btp bin/btp
 
 }
 
 main() {
-
-  # Move to a temporary directory; extract and check version, and
-  # (unless --test mode) install, setting up symlink.
-
-  local desired tempdir ver testmode=false
-
-  # Determine if we're in test mode
-  [[ $1 =~ ^(-t|--test)$ ]] && {
-    testmode=true
-    shift
-  }
-
-  desired="${1:-latest}"
-
-  # Couple of setup activities if we're going to try to install
-  # - make sure the target dir exists
-  # - make sure the user confirms acceptance of the licence
-  if [[ $testmode = false ]]; then
-    [[ ! -d "$TARGETDIR" ]] && mkdir "$TARGETDIR"
-  fi
-
-  # Set up temporary directory and move into it
-  tempdir="$(mktemp -d)"
-
-  # Retrieve latest tarball and extract the binary
-  retrieve "$desired" "$tempdir" || {
-    echo "Failed to find version $desired"
+  retrieve  || {
+    echo "Failed to find version"
     exit 1
   }
-
-  # Determine version
-  ver="$(get_version "$tempdir")"
-  echo "Version is $ver"
-
-  # Unless we're in test mode, move binary to target directory and
-  # set symlink
-  if [[ $testmode = false ]]; then
-    cd "$TARGETDIR" \
-      && mv "$tempdir/btp" "bin/btp"
-  fi
-
-  # Clean up by removing temporary directory
-  rm -rf "$tempdir"
 
 }
 
